name: PHPCS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    name: changed-files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.php

      - name: Remove vendor folder
        run: rm -rf vendor
      
      - name: Install dependencies
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          composer require --dev sirbrillig/phpcs-changed -n
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require --dev woocommerce/woocommerce-sniffs -n

      - name: Run PHP_CodeSniffer
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          HEAD_REF=$(git rev-parse HEAD)
          git checkout $HEAD_REF
          ./vendor/bin/phpcs-changed -s --git --git-base origin/${{ github.base_ref }} ${{ steps.changed-files.outputs.all_changed_files }}